security:
  # Password Hashers
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    api_user_provider:
      entity:
        class: App\Entity\User
        property: token

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api/
      provider: api_user_provider
      custom_authenticator: App\Security\APIAuthenticator
      stateless: true
      lazy: true
    main:
      lazy: true
      provider: app_user_provider

  # Access Control
  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
